spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: metadatagenerator-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

metadatagenerator:
  kafka:
    consumer:
      topic: buffered-post
    producer:
      topic: enriched-post
      dlq-topic: enriched-post-dlq