target:
  url: https://meetup.nhncloud.com/tcblog/v1.0/posts
  source: nhn
  adapter:
    crawler:
      type: nhnCrawler
    extractor:
      type: nhnExtractor
alarm:
  slack:
    enabled: true
nhn:
  per-page: 20