target:
  url: https://tech.socarcorp.kr/posts/
  source: socar
  adapter:
    crawler:
      type: socarCrawler
    extractor:
      type: socarJsoupExtractor
alarm:
  slack:
    enabled: true
socar:
  end-page: 13