target:
  url: https://ridicorp.com/story-category/tech-blog/
  source: ridi
  adapter:
    crawler:
      type: ridiCrawler
    extractor:
      type: ridiExtractor
alarm:
  slack:
    enabled: true
ridi:
  end-page: 3