target:
  url: https://blog.banksalad.com/rss.xml
  source: banksalad
  adapter:
    extractor:
      type: rssExtractor
alarm:
  slack:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

